# Generated by Django 2.1b1 on 2018-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('companyName', models.CharField(max_length=40)),
                ('aboutJob', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
