# Generated by Django 2.1b1 on 2018-07-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20180720_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiences',
            new_name='Experience',
        ),
    ]
