# Generated by Django 2.1b1 on 2018-07-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20180720_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='about',
            new_name='interests',
        ),
    ]
